import type { SelectFieldOption } from "@/components/bank-register/select-field";

const ACCOUNT_OPTIONS_RAW: Array<{ id: string; name: string; category: string }> = [
  { id: "cash-on-hand", name: "Cash on hand", category: "Bank" },
  { id: "credit-card-payable", name: "Credit Card Payable", category: "Credit Card" },
  { id: "charitable-donations", name: "Charitable donations", category: "Equity" },
  { id: "equity-clearing-credit-card-payment", name: "Equity clearing (Credit Card Payment)", category: "Equity" },
  { id: "equity-clearing-transfer", name: "Equity clearing (Transfer)", category: "Equity" },
  { id: "federal-estimated-tax", name: "Federal estimated tax", category: "Equity" },
  { id: "federal-tax", name: "Federal tax", category: "Equity" },
  { id: "health-savings-account", name: "Health Savings Account", category: "Equity" },
  { id: "health-insurance-premium", name: "Health insurance premium", category: "Equity" },
  { id: "mortgage", name: "Mortgage", category: "Equity" },
  { id: "owners-investment", name: "Owners investment", category: "Equity" },
  { id: "owners-pay", name: "Owners pay", category: "Equity" },
  { id: "personal-expense", name: "Personal expense", category: "Equity" },
  { id: "personal-income", name: "Personal income", category: "Equity" },
  { id: "property-tax", name: "Property tax", category: "Equity" },
  { id: "retained-earnings", name: "Retained Earnings", category: "Equity" },
  { id: "retirement-contributions", name: "Retirement contributions", category: "Equity" },
  { id: "state-estimated-tax", name: "State estimated tax", category: "Equity" },
  { id: "state-tax", name: "State tax", category: "Equity" },
  { id: "visits-copays-prescriptions", name: "Visits, copays, and prescriptions", category: "Equity" },
  { id: "advertising-marketing", name: "Advertising and Marketing", category: "Expense" },
  { id: "airfare", name: "Airfare", category: "Expense" },
  { id: "apps-software", name: "Apps and software", category: "Expense" },
  { id: "business-licenses", name: "Business licenses", category: "Expense" },
  { id: "business-loan-interest", name: "Business loan (interest)", category: "Expense" },
  { id: "commissions-fees", name: "Commissions and fees", category: "Expense" },
  { id: "communications", name: "Communications", category: "Expense" },
  { id: "continued-education", name: "Continued education", category: "Expense" },
  { id: "contract-labor", name: "Contract labor", category: "Expense" },
  { id: "credit-card-interest", name: "Credit card interest", category: "Expense" },
  { id: "entertainment", name: "Entertainment", category: "Expense" },
  { id: "equipment-rent-lease", name: "Equipment rent and lease", category: "Expense" },
  { id: "legal-professional-services", name: "Legal and professional services", category: "Expense" },
  { id: "liability-insurance", name: "Liability insurance", category: "Expense" },
  { id: "local-taxes", name: "Local taxes", category: "Expense" },
  { id: "lodging", name: "Lodging", category: "Expense" },
  { id: "materials-supplies", name: "Materials and supplies", category: "Expense" },
  { id: "meals-with-clients", name: "Meals with clients", category: "Expense" },
  { id: "miscellaneous-expenses", name: "Miscellaneous expenses", category: "Expense" },
  { id: "mortgage-interest-business-property", name: "Mortgage interest (business property)", category: "Expense" },
  { id: "office-expenses", name: "Office Expenses", category: "Expense" },
  { id: "other-business-expenses", name: "Other business expenses", category: "Expense" },
  { id: "other-interest", name: "Other interest", category: "Expense" },
  { id: "other-travel-expenses", name: "Other travel expenses", category: "Expense" },
  { id: "property-rents-leases", name: "Property rents and leases", category: "Expense" },
  { id: "property-tax-business-property", name: "Property tax (business property)", category: "Expense" },
  { id: "repairs-maintenance", name: "Repairs and maintenance", category: "Expense" },
  { id: "shipping-fees", name: "Shipping fees", category: "Expense" },
  { id: "subscriptions-memberships", name: "Subscriptions and memberships", category: "Expense" },
  { id: "transaction-fees", name: "Transaction fees", category: "Expense" },
  { id: "travel-meals", name: "Travel meals", category: "Expense" },
  { id: "uncategorized-expense", name: "Uncategorized Expense", category: "Expense" },
  { id: "uniforms", name: "Uniforms", category: "Expense" },
  { id: "utilities-business-property", name: "Utilities (business property)", category: "Expense" },
  { id: "vehicle-rental-public-transportation", name: "Vehicle rental/public transportation", category: "Expense" },
  { id: "apps-software-200", name: "Apps and software (> $200)", category: "Fixed Asset" },
  { id: "building-purchase", name: "Building purchase", category: "Fixed Asset" },
  { id: "computer-200", name: "Computer (> $200)", category: "Fixed Asset" },
  { id: "copier-200", name: "Copier (> $200)", category: "Fixed Asset" },
  { id: "furniture-200", name: "Furniture (> $200)", category: "Fixed Asset" },
  { id: "land-purchase", name: "Land purchase", category: "Fixed Asset" },
  { id: "machinery-equipment", name: "Machinery and equipment", category: "Fixed Asset" },
  { id: "phone-200", name: "Phone (> $200)", category: "Fixed Asset" },
  { id: "photo-video-equipment-200", name: "Photo and video equipment (> $200)", category: "Fixed Asset" },
  { id: "tools-equipment-200", name: "Tools and equipment (> $200)", category: "Fixed Asset" },
  { id: "vehicle-purchase", name: "Vehicle purchase", category: "Fixed Asset" },
  { id: "billable-expense-income", name: "Billable Expense Income", category: "Income" },
  { id: "sales", name: "Sales", category: "Income" },
  { id: "services", name: "Services", category: "Income" },
  { id: "services-6", name: "Services ( 6 )", category: "Income" },
  { id: "uncategorized-income", name: "Uncategorized Income", category: "Income" },
  { id: "business-loan", name: "Business loan", category: "Long Term Liability" },
  { id: "mortgage-principal-business-property", name: "Mortgage principal (business property)", category: "Long Term Liability" },
  { id: "mortgage-principal-home-office", name: "Mortgage principal (home office)", category: "Long Term Liability" },
  { id: "vehicle-loan", name: "Vehicle loan", category: "Long Term Liability" },
  { id: "loans-to-others", name: "Loans to others", category: "Other Current Asset" },
  { id: "uncategorized-asset", name: "Uncategorized Asset", category: "Other Current Asset" },
  { id: "undeposited-funds", name: "Undeposited Funds", category: "Other Current Asset" },
  { id: "sales-tax-to-pay", name: "Sales tax to pay", category: "Other Current Liability" },
  { id: "gas-fuel", name: "Gas and fuel", category: "Other Expense" },
  { id: "homeowner-rental-insurance-home-office", name: "Homeowner/rental insurance (home office)", category: "Other Expense" },
  { id: "mortgage-interest-home-office", name: "Mortgage interest (home office)", category: "Other Expense" },
  { id: "other-home-office-expenses", name: "Other home office expenses", category: "Other Expense" },
  { id: "other-vehicle-expenses", name: "Other vehicle expenses", category: "Other Expense" },
  { id: "parking-tolls", name: "Parking and tolls", category: "Other Expense" },
  { id: "property-tax-home-office", name: "Property tax (home office)", category: "Other Expense" },
  { id: "reconciliation-discrepancies", name: "Reconciliation Discrepancies", category: "Other Expense" },
  { id: "rent-lease-home-office", name: "Rent and lease (home office)", category: "Other Expense" },
  { id: "repairs-maintenance-home-office", name: "Repairs and maintenance (home office)", category: "Other Expense" },
  { id: "utilities-home-office", name: "Utilities (home office)", category: "Other Expense" },
  { id: "vehicle-insurance", name: "Vehicle insurance", category: "Other Expense" },
  { id: "vehicle-lease", name: "Vehicle lease", category: "Other Expense" },
  { id: "vehicle-loan-interest", name: "Vehicle loan interest", category: "Other Expense" },
  { id: "vehicle-registration", name: "Vehicle registration", category: "Other Expense" },
  { id: "vehicle-repairs-maintenance", name: "Vehicle repairs and maintenance", category: "Other Expense" },
  { id: "other-income", name: "Other income", category: "Other Income" }
];

export const ACCOUNT_FIELD_OPTIONS: SelectFieldOption[] = ACCOUNT_OPTIONS_RAW.map((option) => ({
  value: option.name,
  label: option.name,
  rightLabel: option.category,
  keywords: [option.category, option.id]
}));
